kind: PersistentVolume
apiVersion: v1
metadata:
  name: orders-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/orders"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ordersdb
  name: orders-pv
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M